version: "3"
services:
  app:
    build: ./app
    ports:
      - "8443:8443"
      - "8080:80"
    volumes:
      - ./app:/app
    #command: "tail -f /dev/null"
    command: code-server --auth none --host 0.0.0.0 --port 8443 /app
    #command: apache2;tail -f /dev/null

