version: "3"
services:
  app:
    build: ./app
    ports:
      - "8443:8443"
      - "8080:80"
    links:
      - mysqld
    volumes:
      - ./app:/app
    #command: "tail -f /dev/null"
    command: code-server --auth none --host 0.0.0.0 --port 8443 /app
  mysqld: 
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: myapp
    volumes:
      - ./mysqld/:/docker-entrypoint-initdb.d/:rw
  phpmyadmin:
    #https://hub.docker.com/r/phpmyadmin/phpmyadmin
    image: phpmyadmin/phpmyadmin:4.8.5
    environment:
      PMA_HOST: mysqld
      PMA_USER: root
      PMA_PASSWORD: passwd
    links:
      - mysqld
    ports:
      - '18080:80'
